added configuration options for EventStore and Repo
looplab/eventhorizon pull request #260
Opened 2020-09-09 11:25 UTC by Wr4thon

added option for using the dbName instead of the prefix stuff

### Description

With the current implementation the dbName set when creating the client will be used as a template/prefix name.
My Changes added the possibility to just use the name as is, when desired. this will not break existing implementations.

### Affected Components

-Event Store and Repo
No breaking changes, just added optional parameters

### Related Issues

none

### Solution and Design

using optional functions as an additional optional argument when creating the EventStore or the Repo to override the dbName function (with the default value still being the "_" + namespace implementation)

### Steps to test and verify

1. Create a new Instance of the Repo 
2. Pass `repo.DBNameNoPrefix()` as additional parameter.

```
	repo, err := repo.NewRepoWithClient(client, repoConfig.Database, repoConfig.Collection, repo.DBNameNoPrefix())
```

same for the eventStore

2020-09-09 12:47 UTC, Nerzal commented
I like the idea of using functional options to provide a future proof way to configure the behavior

2020-09-09 13:31 UTC, maxekman requested changes
Very nice addition to introduce the config builder pattern!

Could you however change it to use the interface style with a private config method that receives the store as argument? Here is a good example: https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L175

Also change the name of the option to `EventStoreOption`, and the options to `WithDBName` for example.

2020-09-09 13:34 UTC, Wr4thon commented
Hey, thanks.
I will have a look, and come back to you, once I changed it accordingly.

2020-10-02 12:37 UTC, merged

2020-10-02 12:38 UTC, maxekman commented
@Wr4thon I decided to merge it as it was, thanks for the contribution! Don't forget to add yourself to the AUTHORS file if this was your first PR.